# Generated by Django 4.0.5 on 2022-08-12 07:31

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('page_amount', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('current_page', models.IntegerField(validators=[django.core.validators.MaxValueValidator(models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])), django.core.validators.MinValueValidator(1)])),
                ('file', models.FileField(upload_to='media/pdf/')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
