# Generated by Django 4.0.5 on 2022-08-12 07:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='current_page',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(models.IntegerField(blank=True, validators=[django.core.validators.MinValueValidator(1)])), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='book',
            name='page_amount',
            field=models.IntegerField(blank=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
